stages:
  preprocess:
    cmd: python src/data/preprocessing.py
    deps:
      - src/data/preprocessing.py
      - data/raw/fakeReviewData.csv
      - params.yaml
    outs:
      - data/processed/exploration.csv

  preprocess2:
    cmd: python src/data/preprocessing2.py
    deps:
      - src/data/preprocessing2.py
      - data/processed/exploration.csv  # Output of first stage
    outs:
      - data/processed/final_data.csv
